### PR TITLE
Login page added 

### PR DESCRIPTION
**Pull request by Shah-Arsalan**
### Note : 
**Check login inside webpages**

### CODE REVIEW

**Review by Rohanmond — APPROVED** [review]
everything looks good

**Comment by ddivyansh18** [comment]
Looks nice to me !

**Review by ddivyansh18 — APPROVED** [review]

**Review by Aman-Jain1996 — COMMENTED** [review]
Everything looks good but one recommendation to check color contrast ratio of your green color , its not that much readable

**Comment by Shah-Arsalan** [comment]
> Everything looks good but one recommendation to check color contrast ratio of your green color , its not that much readable

Yeah I'll change the primary color at the end

**Pull request merged**
